### ISSUE TITLE
Swap os.sep.join to os.path.join

### ISSUE THREAD

**Issue by dalepotter** [IATI/iati.core#16]
From the [documentation](https://docs.python.org/3.6/library/os.html#os.sep):

```
os.sep

    The character used by the operating system to separate pathname components. This is '/' for POSIX and '\\' for Windows. Note that knowing this is not sufficient to be able to parse or concatenate pathnames — use os.path.split() and os.path.join() — but it is occasionally useful. Also available via os.path.
```

Example of one place where this occurs: https://github.com/IATI/iati.core/blob/69387f84161f4c724fb9fb4b114c1d83bfe80008/iati/core/resources.py#L29

**Comment by hayfield** [comment]
Similarly, instances of `path.split(os.sep)` should be switched to `os.path.split()`
