### ISSUE TITLE
Reduce the verbocity of function calls

### ISSUE THREAD

**Issue by dalepotter** [IATI/iati.core#31]
Currently instantiating a `Dataset` is done using a call to `iati.core.data.Dataset`. This type of thing seems too verbose, and in this example I would suggest that the same could be achieved by `iati.core.Dataset`.

This could be achieved by importing Dataset in to the `iati/core/__init__.py` file, as exemplified by the [Requests library](https://github.com/requests/requests/blob/master/requests/__init__.py#L99-L107).

I would suggest that the following functions have easier calls:

`iati.core.codelists.Code` -> `iati.core.Code`
`iati.core.codelists.Codelist` -> `iati.core.Codelist`
`iati.core.data.Dataset` -> `iati.core.Dataset`
`iati.core.rulesets.Rule` -> `iati.core.Rule`
`iati.core.rulesets.Ruleset ` -> `iati.core.Ruleset`
`iati.core.schema.Schema` -> `iati.core.Schema`

**Comment by dalepotter** [comment]
This is now merged into dev, so will be can be closed when `dev` is next merged to the `master` branch.

**Comment by hayfield** [comment]
Since it's in dev, will close this
