### ISSUE TITLE
Rename iati.core.tests.utilities.find_parameter_by_type

### ISSUE THREAD

**Issue by dalepotter** [IATI/iati.core#63]
The function `iati.core.tests.utilities.find_parameter_by_type` provides a means of generating various object types for use in test fuzzing.

For clarity, I would suggest renaming this to `iati.core.tests.utilities.get_test_types`, or `iati.core.tests.utilities.generate_test_types`.

The parameter `type_as_specified=True` could also be renamed to `invert_types=False` (with appropriate change to https://github.com/IATI/iati.core/blob/dev/iati/core/tests/utilities.py#L108)

Suggest doing this after https://github.com/IATI/iati.core/pull/57 has been merged to `dev`, to avoid issues with merge conflicts.

**Comment by hayfield** [comment]
Two find+replace regex pairs for conversion:

* `iati\.core\.tests\.utilities\.find_parameter_by_type\((\[(.*,?\s?)?\]),\s?False\)` -> `iati\.core\.tests\.utilities\.generate_test_types\($1, True\)`
* `iati\.core\.tests\.utilities\.find_parameter_by_type\((\[(.*,?\s?)?\]),\s?True\)` -> `iati\.core\.tests\.utilities\.generate_test_types\($1, False\)`
